// Code generated by sqlc. DO NOT EDIT.
// source: test.sql

package db

import (
	"context"
)

const testUser = `-- name: TestUser :one
SELECT name, created_at FROM test_table
WHERE name = $1
LIMIT 1
`

func (q *Queries) TestUser(ctx context.Context, name string) (TestTable, error) {
	row := q.db.QueryRowContext(ctx, testUser, name)
	var i TestTable
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}
